import Header from '@/components/Header';
import Providers from './Providers'
import './globals.css'
import ScrollButton from '@/components/ScrollButton';

export const metadata = {
  title: "Cruise R Nah app.",
  description: "Is it a movie Tom Cruise starred in, or nah? Generated by create next app."
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Providers>

          {/* Header */}
          <Header />

          {children}
          <ScrollButton />
        </Providers>
      </body>
    </html>
  );
}
