import Header from '@/components/Header';
import Providers from './Providers'
import './globals.css'

export const metadata = {
  title: "Cruise R Nah app.",
  description: "Is it a movie Tom Cruise starred in, or nah? Generated by create next app."
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Providers>
          {/* Header */}
          <Header />

          {/* Navbar */}

          {/* Search */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
