import './globals.css'
import { Inter } from 'next/font/google'

export const metadata = {
  title: "Cruise R Nah app.",
  description: "Is it a movie Tom Cruise starred in, or nah? Generated by create next app."
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
      {/* Header */}

      {/* Navbar */}

      {/* Search */}
      {children}
      </body>
    </html>
  )
}
